config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :missions, only: [:new, :create, :destroy] do
  resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crew_member.rb
class CrewMember < ApplicationRecord
  has_many :orders, dependent: :delete_all
  has_many :missions, through: :orders
  validates :name, presence: true
  validates :position, presence: true
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :orders, dependent: :delete_all
  has_many :crew_members, through: :orders
  validates :name, presence: true
  validates :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :crew_member
  belongs_to :mission
  validates :mission_id, uniqueness: { scope: :crew_member_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def new
    @mission = Mission.new
  end

  def show
    @mission = Mission.find(params[:id])
  end

  def create
    @mission = Mission.new(mission_params)
    if @mission.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy
    redirect_to root_path
  end

  private

  def mission_params
    params.require(:mission).permit(:name, :description)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @mission = Mission.find(params[:mission_id])
    @crew_members = CrewMember.where.not(id: @mission.crew_members).order(name: :asc)
  end

  def create
    @order = Order.new(order_params)
    @mission = Mission.find(params[:mission_id])
    @order.mission = @mission
    if @order.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:comment, :crew_member_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @crew_members = CrewMember.all
    @missions = Mission.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space Wagon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag image_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/_mission_form.html.erb
<%= simple_form_for @mission do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit 'Add mission', class: 'btn btn-light' %>
<% end %>

app/views/missions/new.html.erb
<div class="container my-4">
  <h1>Add a new mission for the crew members</h1>
  <%= render 'mission_form' %>
</div>

app/views/orders/_order_form.html.erb
<%= simple_form_for [@mission, @order] do |f| %>
    <%= f.input :comment %>
    <%= f.association :crew_member, as: :radio_buttons, include_blank: false, collection: @crew_members %>
    <%= f.submit 'Add crew member', class: 'btn btn-light' %>
<% end %>

app/views/orders/new.html.erb
<div class="container my-4">
  <h1>Add a crew member to the "<%= @mission.name %>" mission</h1>
  <%= render 'order_form' %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <div>
      <h1>Spacewagon 🚀</h1>
      <p><span data-controller="typed-js"></span></p>
    </div>
    <%= link_to 'Assign new mission', new_mission_path, class: 'btn btn-light' %>
  </div>
</div>
<div class="container my-4">
  <h2>The Wagon Crew</h2>
  <div class="cards my-3">
    <% @crew_members.each do |member| %>
      <div class="card-product">
        <img src="<%= member.photo_url %>"  />
        <div class="card-product-infos">
          <h3><%= member.name %></h3>
          <p><strong><%= member.position %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex align-items-baseline gap-2">
    <h2 class="mt-3">Pending missions</h2>
    <%= link_to new_mission_path, class: 'card-mission-link' do%>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <% if Mission.all.empty? %>
    <p>No missions yet...</p>
  <% else %>
    <div class="cards my-3">
      <% @missions.each do |mission| %>
        <div class="card"> 
          <div class="card-body">
            <h5 class="card-title"><strong><%= mission.name %></strong></h5>
            <h3 class="card-text"><%= mission.description %></h3>
            <br>
            <h4><strong>Assigned crew:</strong></h4>
          </div>
          <ul class="list-group list-group-flush">
            <% mission.orders.each do |order| %>
            <li class="list-group-item">
              <div class="d-flex align-items-center gap-2">
                <%= image_tag order.crew_member.photo_url, class: 'avatar' %>
                <div class="flex-grow-1">
                  <p class="m-0"><strong><%= order.crew_member.name %></strong></p>
                  <p class="m-0 opacity-75"><%= order.comment.empty? ? 'No comment added...' : order.comment %></p>
                </div>
                <%= link_to order_path(order), data: { turbo_method: :delete, turbo_confirm: "Remove #{order.crew_member.name}?" }, class: 'card-remove-link' do %>
                  <i class="fa-solid fa-user-minus"></i>
                <% end %>
              </div>
              
            </li>
            <% end %>
          </ul>
          <%= link_to 'Add crew member', new_mission_order_path(mission), class: 'btn btn-light' %>
          <%= link_to mission_path(mission), data: { turbo_method: :delete, turbo_confirm: "Cancel mission?" }, class: 'card-cancel-link' do %>
            <i class="fa-solid fa-x"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>